Data Preprocessing Tools

In [68]:
# Importing The libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [69]:
#importing the dataset
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [70]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [71]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [72]:
#creating Pandas Dataframe
dataframe = pd.DataFrame(dataset)
dataframe

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Taking Care Of Missing Values

In [73]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.nan, strategy= 'mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

Encoding Categorical Data

In [74]:
#Endicoding the Independant Variables
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
columnTrans = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(columnTrans.fit_transform(X))
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [75]:
#Encoding the Dependant Variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

Splitting the Dataset into Test and Train set

In [76]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)
X_train

array([[1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0]], dtype=object)

In [77]:
X_test

array([[0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 1.0, 27.0, 48000.0]], dtype=object)

In [78]:
y_train

array([1, 0, 1, 0, 0, 0, 1, 0])

In [79]:
y_test

array([1, 1])

Feature Scaling

In [85]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train[:, 3:])
X_train[:, 3:] = sc.transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [86]:
print(X_train)

[[1.0 0.0 0.0 -0.8066752374797971 -0.7213204519277457]
 [1.0 0.0 0.0 0.6176450728387547 0.5817100418772143]
 [1.0 0.0 0.0 1.250676321869222 1.2332252887796944]
 [0.0 1.0 0.0 -1.5979642987678815 -1.093614878729163]
 [0.0 0.0 1.0 -0.3319018007069464 -0.4420996318266829]
 [0.0 0.0 1.0 -0.2088123911732443 -1.2797620921298716]
 [1.0 0.0 0.0 -0.49015961296456323 0.11634200837544292]
 [0.0 1.0 0.0 1.5671919463844557 1.6055197155811116]]


In [87]:
print(X_test)

[[0.0 1.0 0.0 -0.015386176191712708 -0.1835618354368095]
 [0.0 0.0 1.0 -2.072737735540732 -1.6520565189312888]]
